### ISSUE TITLE
Concurrent, wait-free Stack

### ISSUE THREAD

**Issue by SamyFrancelet** [SamyFrancelet/pcm_tsp#3]
Create and test a concurrent wait-free stack

**Comment by landry-r** [comment]
In [this](https://github.com/SamyFrancelet/pcm_tsp/commit/4ba5a9805728add7e16f676c1cd687d54c892bf4) commit, a concurrent stack has been created. The stack has been tested with test_stack.cpp which create 4 threads, two push X time and two pop X time, at the end if the stack is empty the test passed.
The MakeFile has been updated to compile the test file.
